---
ID: "7842eb37-4557-4dd9-8086-c3ce0e343045"
Parent: "340a2d29-8e92-48da-a21e-e158442d69ae"
Template: "340a2d29-8e92-48da-a21e-e158442d69ae"
Path: /sitecore/templates/Starter/Foundation/Serialization/Module Node/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20171103T165755Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
