---
ID: "b8837163-4cf6-4aa1-8960-3b7708c27721"
Parent: "7fdbc483-cbc7-41a0-9566-795ceffd9eb2"
Template: "340a2d29-8e92-48da-a21e-e158442d69ae"
Path: /sitecore/content/Starter/Project
DB: master
SharedFields:
- ID: "06d5295c-ed2f-4a54-9bf2-26228d113318"
  Hint: __Icon
  Value: People/32x32/cube_blue.png
- ID: "9c6106ea-7a5a-48e2-8cad-f0f693b1e2d4"
  Hint: __Read Only
  Type: Checkbox
  Value: 0
- ID: "dec8d2d5-e3cf-48b6-a653-8e69e2716641"
  Hint: __Security
  Value: |
    ar|Starter\Everyone|pe|!*|pd|!*|ar|Starter\ProjectAuthor|pd|+item:rename|+item:delete|+item:write|+item:create|ar|Starter\ProjectViewer|pe|+item:read|pd|+item:read|
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20170929T140425Z
